import { Inter } from "next/font/google";
import "./globals.css";
import "nprogress/nprogress.css";
import dynamic from 'next/dynamic';
import { RouterGuard } from '../components/RouteGuard';
import { Montserrat } from 'next/font/google';
import { Nunito } from 'next/font/google';
const nunito = Nunito({ subsets: ['latin'] })

// const TopProgressBar = dynamic(
//   () => {
//     return import("../components/TopProgressBar");
//   },
//   { ssr: false },
// );
import NextTopLoader from 'nextjs-toploader';

export const metadata = {
  title: "Nextjs 14 Template",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="shortcut icon" href="/favicon.ico" />
        <link rel='manifest' href='/manifest.json' />
        <link rel='apple-touch-icon' href='/icon.png' />
        <meta name='theme-color' content='#fff' />
        <meta name="robots" content="index,follow"/>
        <meta name="keywords" content="app, template, agrayasa, global, industri" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
      </head>
      <body className={nunito.className}>
      <NextTopLoader />
      <RouterGuard>
        {children}
      </RouterGuard>
        
        </body>
    </html>
  );
}
